frr version 10.6.1
frr defaults traditional
hostname edge2
service integrated-vtysh-config
!
interface lo
 ip address 10.255.4.4/32
!
interface eth1
 ip address 192.168.30.1/31
 ip ospf cost 10
 ip ospf network point-to-point
 ip ospf mtu-ignore
 ip ospf hello-interval 1
 ip ospf dead-interval 3
!
router ospf
 ospf router-id 10.255.4.4
 passive-interface lo
 network 10.255.4.4/32 area 0
 network 192.168.30.0/31 area 0
!
router bgp 65002
 no bgp ebgp-requires-policy
 bgp router-id 10.255.4.4
 neighbor 192.168.30.0 remote-as 65000
 !
 address-family ipv4 unicast
  network 10.255.4.4/32
  neighbor 192.168.30.0 activate
 exit-address-family
exit
!
