frr version 10.6.1
frr defaults traditional
hostname core1
service integrated-vtysh-config
!
interface lo
 ip address 10.255.2.2/32
!
interface eth1
 ip address 192.168.10.1/31
 ip ospf cost 10
 ip ospf network point-to-point
 ip ospf mtu-ignore
 ip ospf hello-interval 1
 ip ospf dead-interval 3
!
interface eth2
 ip address 192.168.20.0/31
 ip ospf cost 10
 ip ospf network point-to-point
 ip ospf mtu-ignore
 ip ospf hello-interval 1
 ip ospf dead-interval 3
!
router ospf
 ospf router-id 10.255.2.2
 passive-interface lo
 network 10.255.2.2/32 area 0
 network 192.168.10.0/31 area 0
 network 192.168.20.0/31 area 0
!
router bgp 65000
 no bgp ebgp-requires-policy
 bgp router-id 10.255.2.2
 neighbor 192.168.10.0 remote-as 65001
 neighbor 192.168.20.1 remote-as 65000
 !
 address-family ipv4 unicast
  neighbor 192.168.10.0 activate
  neighbor 192.168.20.1 activate
 exit-address-family
exit
!
