frr version 10.6.1
frr defaults traditional
hostname r2
service integrated-vtysh-config
!
interface eth1 vrf tenant-a
 ip address 192.0.2.2/30
 ip ospf area 0
!
interface a-svc vrf tenant-a
 ip address 10.10.0.1/32
!
router ospf vrf tenant-a
 ospf router-id 10.255.2.2
 passive-interface a-svc
 network 192.0.2.0/30 area 0
 network 10.10.0.1/32 area 0
!
