frr version 10.6.1
frr defaults traditional
hostname r3
service integrated-vtysh-config
!
interface eth1 vrf tenant-b
 ip address 192.0.2.2/30
!
interface b-svc vrf tenant-b
 ip address 10.255.0.1/32
!
interface b-only vrf tenant-b
 ip address 10.66.0.1/32
!
