frr version 10.6.1
frr defaults traditional
hostname r2
service integrated-vtysh-config
!
interface eth1 vrf tenant-a
 ip address 192.0.2.2/30
!
interface a-svc vrf tenant-a
 ip address 10.255.0.1/32
!
