frr version 10.6.1
frr defaults traditional
hostname r1
service integrated-vtysh-config
!
interface eth1 vrf tenant-a
 ip address 192.0.2.1/30
!
interface eth2 vrf tenant-b
 ip address 192.0.2.1/30
!
ip route 10.255.0.1/32 192.0.2.2 vrf tenant-a
ip route 10.255.0.1/32 192.0.2.2 vrf tenant-b
ip route 10.66.0.1/32 192.0.2.2 vrf tenant-b
!
