frr version 10.6.1
frr defaults traditional
hostname a
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.1/32
!
interface eth1
 ip address 192.168.1.0/31
!
interface eth2
 ip address 192.168.3.0/31
!
bgp community-list standard TAG300 permit 300:300
!
route-map TAG-FROM-C permit 10
 set community 300:300
!
route-map SET-LOCALPREF permit 10
 match community TAG300
 set local-preference 600
!
route-map SET-LOCALPREF permit 20
!
router bgp 100
 no bgp ebgp-requires-policy
 bgp router-id 10.255.0.1
 neighbor 192.168.1.1 remote-as 300
 neighbor 192.168.1.1 route-map TAG-FROM-C import
 neighbor 192.168.3.1 remote-as 100
 neighbor 192.168.3.1 route-map SET-LOCALPREF export
 !
 address-family ipv4 unicast
  neighbor 192.168.1.1 activate
  neighbor 192.168.3.1 activate
 exit-address-family
exit
!
