frr version 10.6.1
frr defaults traditional
hostname b
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.2/32
!
interface eth1
 ip address 192.168.2.0/31
!
interface eth2
 ip address 192.168.3.1/31
!
router bgp 100
 no bgp ebgp-requires-policy
 bgp router-id 10.255.0.2
 neighbor 192.168.2.1 remote-as 200
 neighbor 192.168.3.0 remote-as 100
 !
 address-family ipv4 unicast
  neighbor 192.168.2.1 activate
  neighbor 192.168.3.0 activate
 exit-address-family
exit
!
