frr version 10.6.1
frr defaults traditional
hostname r3
service integrated-vtysh-config
!
interface eth1 vrf tenant-b
 ip address 198.51.100.2/30
 ip ospf area 0
!
interface b-svc vrf tenant-b
 ip address 10.20.0.1/32
!
router ospf vrf tenant-b
 ospf router-id 10.255.3.3
 passive-interface b-svc
 network 198.51.100.0/30 area 0
 network 10.20.0.1/32 area 0
!
