frr version 10.6.1
frr defaults traditional
hostname r1
service integrated-vtysh-config
!
interface eth1 vrf tenant-a
 ip address 192.0.2.1/30
 ip ospf area 0
!
interface eth2 vrf tenant-b
 ip address 198.51.100.1/30
 ip ospf area 0
!
router ospf vrf tenant-a
 ospf router-id 10.255.1.1
 network 192.0.2.0/30 area 0
!
router ospf vrf tenant-b
 ospf router-id 10.255.1.2
 network 198.51.100.0/30 area 0
!
